import React, { FC } from "react";
import {
  View,
  Image,
  Text,
  ScrollView,
  StyleSheet,
  Linking,
  TouchableOpacity,
  Button,
} from "react-native";
// @ts-ignore
import EmptyBox from "../../../assets/ICONS/emptycheckbox.png";
// @ts-ignore
import Checkbox from "../../../assets/ICONS/checkedbox.png";

type TermProps = {
  setTermsOfServices: React.Dispatch<React.SetStateAction<boolean>>;
  setShowTerms: React.Dispatch<React.SetStateAction<boolean>>;
  termsOfServicces: boolean;
};

const Terms: FC<TermProps> = ({
  setTermsOfServices,
  setShowTerms,
  termsOfServicces,
}) => {
  return (
    <ScrollView style={styles.container}>
      <View style={styles.wrapper}>
        <Text style={styles.header}>Privacy Policy</Text>
        <Text style={styles.text}>Last updated: June 03, 2024</Text>
        <Text style={styles.text}>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Text>
        <Text style={styles.text}>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the{" "}
          <Text
            style={styles.link}
            onPress={() =>
              Linking.openURL(
                "https://www.termsfeed.com/privacy-policy-generator/"
              )
            }
          >
            Privacy Policy Generator
          </Text>
          .
        </Text>
        <Text style={styles.subHeader}>Interpretation and Definitions</Text>
        <Text style={styles.subSubHeader}>Interpretation</Text>
        <Text style={styles.text}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Text>
        <Text style={styles.subSubHeader}>Definitions</Text>
        <Text style={styles.text}>
          For the purposes of this Privacy Policy:
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Account</Text> means a unique account
          created for You to access our Service or parts of our Service.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Affiliate</Text> means an entity that
          controls, is controlled by or is under common control with a party,
          where "control" means ownership of 50% or more of the shares, equity
          interest or other securities entitled to vote for election of
          directors or other managing authority.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Application</Text> refers to MyKeyBox.com,
          the software program provided by the Company.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Company</Text> (referred to as either "the
          Company", "We", "Us" or "Our" in this Agreement) refers to MyKeyBox
          LLC, 7565 haverhill ln,Maineville,Ohio.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Country</Text> refers to: Ohio, United
          States
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Device</Text> means any device that can
          access the Service such as a computer, a cellphone or a digital
          tablet.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Personal Data</Text> is any information that
          relates to an identified or identifiable individual.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Service</Text> refers to the Application.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Service Provider</Text> means any natural or
          legal person who processes the data on behalf of the Company. It
          refers to third-party companies or individuals employed by the Company
          to facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>Usage Data</Text> refers to data collected
          automatically, either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page
          visit).
        </Text>
        <Text style={styles.listItem}>
          <Text style={styles.bold}>You</Text> means the individual accessing or
          using the Service, or the company, or other legal entity on behalf of
          which such individual is accessing or using the Service, as
          applicable.
        </Text>
        <Text style={styles.subHeader}>
          Collecting and Using Your Personal Data
        </Text>
        <Text style={styles.subSubHeader}>Types of Data Collected</Text>
        <Text style={styles.subSubHeader}>Personal Data</Text>
        <Text style={styles.text}>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </Text>
        <Text style={styles.listItem}>Email address</Text>
        <View style={styles.termsOfServicesWrapper}>
          <View style={styles.checkBoxWrapper}>
            <TouchableOpacity
              onPress={() => setTermsOfServices(!termsOfServicces)}
            >
              <Image
                style={styles.checkBox}
                source={termsOfServicces ? Checkbox : EmptyBox}
              />
            </TouchableOpacity>
            <Text style={styles.termsOfServiceText}>
              I accept to the Terms of Use
            </Text>
          </View>
          <TouchableOpacity
            onPress={() => setShowTerms(false)}
            style={{ width: "100%" }}
          >
            <Text style={styles.closeBtn}>Close</Text>
          </TouchableOpacity>
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    height: "90%",
    width: "92%",
    backgroundColor: "#0d90ff",
    padding: 10,
    paddingBottom: 20,
    paddingTop: 20,
    position: "absolute",
    top: 30,
    zIndex: 1002,
    borderRadius: 20,
  },
  wrapper: {
    backgroundColor: "#fff",
    padding: 30,
    borderRadius: 10,
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#0d90ff",
  },
  subHeader: {
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 10,
  },
  subSubHeader: {
    fontSize: 18,
    fontWeight: "bold",
    marginVertical: 5,
  },
  text: {
    fontSize: 16,
    marginVertical: 5,
  },
  listItem: {
    fontSize: 16,
    marginVertical: 5,
    paddingLeft: 20,
  },
  bold: {
    fontWeight: "bold",
  },
  link: {
    color: "blue",
    textDecorationLine: "underline",
  },
  termsOfServicesWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    justifyContent: "center",
    width: "90%",
  },
  checkBoxWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  checkBox: { width: 25, height: 25 },
  termsOfServiceText: {
    fontSize: 18,
    color: "black",
  },
  closeBtn: {
    backgroundColor: "#0d90ff",
    color: "white",
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 5,
    textAlign: "center",
    fontSize: 16,
  },
  termsOfServiceRoute: {
    color: "orange",
    textDecorationLine: "underline",
  },
});
export default Terms;
